### ISSUE TITLE
Spelling error in monitoring mode output?

### ISSUE THREAD

**Issue by Moredread** [erpalma/throttled#102]
When running in monitoring mode I e.g. get

```
[AC] Thermal: OK - Power: OK - Current: OK - Cross-comain (e.g. GPU): OK  ||  VCore: 1373 mV - Package: 4.2 W - Graphics: 0.1 W - DRAM: 0.3 W
```

Shouldn't it be Cross-domain, instead of Cross-comain? I wanted to ask before I create a PR.

**Comment by erpalma** [comment]
It made me laugh that you misspelled "spelling" in the title :)

Thanks for pointing this out!
