### ISSUE TITLE
Use copr build rpm for Fedora

### ISSUE THREAD

**Issue by abn** [erpalma/throttled#106]
Created a copr package for use on Fedora. This can be installed as follows for Fedora 28 and 29.

```sh
dnf copr enable abn/throttled
dnf install -y throttled

systemctl enable throttled
systemctl start throttled
```

Source: https://github.com/abn/throttled-rpm
Copr Repo: https://copr.fedorainfracloud.org/coprs/abn/throttled/

This has only been tested on my machine. But happy to fix any issues reported.

**Comment by erpalma** [comment]
Can you do PR for this? :)
