### ISSUE TITLE
Explanation of undervolt syntax.

### ISSUE THREAD

**Issue by StarrKiss** [erpalma/throttled#131]
Say I want to undervolt by 120 mv.
Would I do it like this:
[UNDERVOLT.BATTERY]
# CPU core voltage offset (mV)
CORE: -120

Or like this:
[UNDERVOLT.BATTERY]
# CPU core voltage offset (mV)
CORE: 120

Or even like this:

[UNDERVOLT.BATTERY]
# CPU core voltage offset (mV)
CORE: 120mv

?

**Comment by erpalma** [comment]
Use the markdown code tag please. As you can see in the README the correct syntax is `CORE: -120`.
