### ISSUE TITLE
It seems that removing the Intel Management Engine SOLVES Thermal Throttling Issues

### ISSUE THREAD

**Issue by CodeDragon5793** [erpalma/throttled#174]
Using the me_cleaner tool, I disabled the Intel Management Engine on my ThinkPad T480. Upon immediate reboot I noticed what appeared to be improved thermals. Thus I decided to test it. I removed the throttled daemon from my system completely and ran a five minute stress test using s-tui. This is still preliminary results. I don't know what else will come of this.
![Screenshot_from_2020-02-06_03-31-26](https://user-images.githubusercontent.com/60212248/73924255-187f3080-48c4-11ea-8d01-e6769df526d1.png)

For more information on what I did visit: https://github.com/corna/me_cleaner/issues/3 and https://github.com/corna/me_cleaner/wiki/External-flashing

**Comment by CodeDragon5793** [comment]
FYI Hyperthreading on my system is disabled because of Zombieload

**Comment by CodeDragon5793** [comment]
Note: My laptop was plugged in during that test.

**Comment by CodeDragon5793** [comment]
The Intel ME doesn't stay disabled.

**Comment by asvc** [comment]
> The Intel ME doesn't stay disabled.

Do you mean that `HAP` bit somehow reverts back?

**Comment by jonathanpopham** [comment]
Hello, @CodeDragon5793  can you please clarify if the HAP bit reverts? Was this unsuccessful? I am considering a t480 but I don't want to buy one if ME cannot be disabled.
