### ISSUE TITLE
Thank you so much!

### ISSUE THREAD

**Issue by deadraid** [erpalma/throttled#178]
Thank you so much!
Solved the problem with throttling on Asus N551VW.
Ubuntu 19.10

**Comment by erpalma** [comment]
I'm glad I helped ;)

**Comment by hellofaduck** [comment]
Happy to find this issue! )) You does so much work around this stupid problem ans share with others, i am really appreciate for this! Recently i bought T480 and trying move to linux from win10, and without your tool it was nearly impossible to do this and archive same performance on this not cheap laptop. Thanks twice for saving my investment in this hardware :)
