### ISSUE TITLE
Undervolting worsen performance on battery

### ISSUE THREAD

**Issue by CoolLamer** [erpalma/throttled#181]
When I undervolt on AC everything working as expected.

But on the battery under load CPU using lover frequencies and lower TPD.

I'm using sysbench for performance measuring (`sysbench cpu --threads=8 run`)

Standard Voltage:
- Cpu Reaching 2.1Ghz
- Sysbech: 4721
```
[I] Detected CPU architecture: Intel Kaby Lake (R)
[I] Loading config file.
[I] Starting main loop.
[D] Undervolt offsets: CORE: 0.00 mV | GPU: 0.00 mV | CACHE: 0.00 mV | UNCORE: 0.00 mV | ANALOGIO: 0.00 mV
[D] IccMax: CORE: 64.00 A | GPU: 31.00 A | CACHE: 6.00 A
[D] Realtime monitoring of throttling causes:

[BATTERY] Thermal: OK - Power: OK - Current: OK - Cross-domain (e.g. GPU): OK  ||  VCore: 807 mV - Package: 13.3 W - Graphics: 0.6 W - DRAM: 0.8 W 
```

Undervolted:
- Cpu Reaching 1.8Ghz
- Sysbech: 4123
```
[I] Detected CPU architecture: Intel Kaby Lake (R)
[I] Loading config file.
[I] Starting main loop.
[D] Undervolt offsets: CORE: -85.00 mV | GPU: -80.00 mV | CACHE: -80.00 mV | UNCORE: -80.00 mV | ANALOGIO: -80.00 mV
[D] IccMax: CORE: 64.00 A | GPU: 31.00 A | CACHE: 6.00 A
[D] Realtime monitoring of throttling causes:

[BATTERY] Thermal: OK - Power: OK - Current: OK - Cross-domain (e.g. GPU): OK  ||  VCore: 672 mV - Package: 8.1 W - Graphics: 0.4 W - DRAM: 0.6 W 
```

I'm using Lenovo T480 I7-8550u with integrated gpu.

I expected that it should behave same on the battery like on AC (same tpd, higher frequency = more performance), do I understand it correctly and is it realy bug or wrong configration ?

I use default config from arch linux package throttled, i changed only the values for the battery.

**Comment by erpalma** [comment]
I guess your problem is related to the `balance_power` energy performance preference used when on battery. Try setting it to `balance_performance` or `performance` (this will drain your battery very fast tough) and repeat your tests. 

On battery, TLP disabled and `balance_performance` I get:
- `7763.29` without undervolt
- `8346.28` with undervolt

Also use `--time=120` to make the test run longer so to produce more stable results.
