### ISSUE TITLE
The tool works on Thinkpad X270

### ISSUE THREAD

**Issue by muniter** [erpalma/throttled#188]
I must thank you all very much for creating this tool, it has saved my laptop. I had problems with throttling to 400 Mhz when on battery, for a long time. And since I installed this tool, around 2 months ago. Haven't had the issue once. Battery life is just as good. **Thank you thank you thank you!** I was thinking about replacing my laptop.

Laptop: Lenovo Thinkpad X270
Model: 20HMA0GM00
CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

**Comment by erpalma** [comment]
Thank you for the feedback ;)

**Comment by CR000K** [comment]
Hello @muniter , can you share your settings to this laptop?

Thank you very much :).
