### ISSUE TITLE
Did not help, but you might consider adding my finding to the readme page

### ISSUE THREAD

**Issue by marcwittke** [erpalma/throttled#193]
Whole story with my Dell Latitude 5591 (i7-8850H):
https://unix.stackexchange.com/questions/579159

### tl;dr
The Windows only tool _Dell Power Manager_ stores it's settings on the system board, not in config files. The profile `Quiet` will, once activated, be persisted for the system's lifetime, in my case resulting in short-time Pmax of 25W, long-time Pmax of 15W

**Comment by erpalma** [comment]
Yes, that happens on Lenovo too. Feel free to do a PR for this!

**Comment by marcwittke** [comment]
done
