### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by evan-goode** [erpalma/throttled#204]
You have no idea how many years of frustration this has solved. My previous solution to avoid throttling was having a keyboard shortcut to lock my laptop's fans to max speed and limit the CPU to 2GHz, and just pray that it wasn't too hot in the room. Holy shit.

Confirmed working on a MacBookPro11,5, Arch Linux.

**Comment by Yacodo** [comment]
Effin awesome dudes ! Feels like getting from 56k to optic fiber.

I'm confirming it works good on a Thinkpad P15s Gen1 w/ fresh Fedora 34 using the COPR method provided by the README. 

I just had to remove thermald (it was conflicting) 
> `sudo dnf remove thermald`
