### ISSUE TITLE
HWP mode is not resetting back to balance_performance

### ISSUE THREAD

**Issue by Rush** [erpalma/throttled#213]
Hey, I was just playing with `HWP` mode and watching the clocks on `s-tui`. Unfortunately when load stops, throttled does not seem to reset back `balane_performance`. Restarting `tlp` fixes it ... but I would expect `throttled` to manage it by itself.

I was reading the code and indeed I don't see any code which would put it back into performance.

**Comment by erpalma** [comment]
HWP is not set to performance (i.e. 0x0) but to a specific intermediate value, 0x20. With this value the CPU is still allowed to go back to low frequency in idle, like in balance_performance mode, but can also clock as high as it can when loaded like in performance mode. This way we don't need to constantly adjust this value based on CPU load. See 95aa5b1.
