### ISSUE TITLE
Fedora 33 note: dbus-python won't build under python3.9, workaround is to use python3.8

### ISSUE THREAD

**Issue by timrichardson** [erpalma/throttled#224]
Hi, Fedora33 uses python3.9 and dbus-python doesn't build.

I did this:
```
sudo dnf install python3.8
```
then cloned this repo and edit install.sh to specify python3.8 in the line which makes the venv

Note: you should completely remove any existing installation of throttled because you need the install script to make a pristine venv in /opt/lenovo_fix

**Comment by erpalma** [comment]
Actually this is already fixed, see #217.

**Comment by timrichardson** [comment]
thanks I can build it now,
