### ISSUE TITLE
lenovo_fix write to unrecognized MSR

### ISSUE THREAD

**Issue by AdrianDeAnda** [erpalma/throttled#225]
After upgrading the kernel while running the `lenovo_fix.service` I get this issue every few seconds. In the meantime I have disabled the service.

```
[69.128297] msr: Write to unrecognized MSR 0x1a2 by python3
[69.128297] Please report to x86@kernel.org
```

Hardware:

```
Lenovo Thinkpad X1 Carbon 6th Gen
OS: Arch Linux 
Kernel: 5.9.4-zen1-1-zen 
CPU: Intel i7-8550U (8) @ 4.0GHz 
GPU: Intel UHD Graphics 620 
```

**Comment by januszmk** [comment]
@AdrianDeAnda https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=x86/misc&id=a7e1f67ed29f0c339e2aa7483d13b085127566ab try adding allow_writes=on parameter

**Comment by LinuxOnTheDesktop** [comment]
This issue is a duplication of #215.

**Comment by AdrianDeAnda** [comment]
> This issue is a duplicate of #215.
