### ISSUE TITLE
Undervolt does not work 

### ISSUE THREAD

**Issue by boytunp** [erpalma/throttled#233]
[D] cpu platform info: feature low power mode = 1
[D] Undervolt plane CORE - write -70 mV (0xf7000000) - read 0 mV (0x0) - match ERR
[D] Undervolt plane GPU - write 0 mV (0x0) - read 0 mV (0x0) - match OK
[D] Undervolt plane CACHE - write -70 mV (0xf7000000) - read 0 mV (0x0) - match ERR

processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
stepping	: 12
microcode	: 0xde

**Comment by boytunp** [comment]
disabled by bios, common in 10th gen cpus

**Comment by erpalma** [comment]
Good to know thank you.
