### ISSUE TITLE
Support for Tiger Lake

### ISSUE THREAD

**Issue by Oisangui** [erpalma/throttled#241]
I am not able to start the daemon because the i7-1185G7 is not supported. I understand the 11th gen processors can't be undervolted, however, it would be good if the non undervolt capabilities were available.

**Comment by erpalma** [comment]
I guess you are right. Are you sure that you can change other settings on 11th gen though?

**Comment by Oisangui** [comment]
Yes. For example, I am using the Dell Latitude 7420 shipped with Ubuntu 20.04. I dual booted with Windows because I was frustrated with the thermal throttling in Ubuntu which caused the CPU to stick to 60C.

The thing is, in Windows there is no issue at all. My CPU happily goes to a full 100C for quite a lot of time, which is expected if you want the best performance.

Now, if Windows can do it, why couldn't Linux as well?

**Comment by erpalma** [comment]
With the latest commit if you omit `[UNDERVOLT]`, `[UNDERVOLT.AC]` and `[UNDERVOLT.BATTERY]` from config file, undervolt won't be applied.
