### ISSUE TITLE
Tested on HP Probook 450 G5

### ISSUE THREAD

**Issue by the-rectifier** [erpalma/throttled#246]
Just like the other user who tested on the 470 G5, i have an i5-8250. I had issues with my CPU not boosting enough, no power draw, no fan speed up, temps never went  above 60 deg C.

This tool fixed everything! (with no extra configuration at all) The CPU is now boosting up to 3.2 GHz for 5mins under an all-core  stress test and then throttles down to 3.0 GHz when the temps get to high 95+ deg C, which i have never experienced before on this laptop under Linux. 

In BIOS i only disabled the option "Fan ON always while on AC power" which supposedly lets the OS have a better control over the fan. (from hp forums). 

Running Arch, and the latest BIOS from HP (Q85 Ver. 01.15.00)

I spent almost 3 years trying to fix this and never came across this tool, thank you for your work.

Please update the description on the supported notebooks (this tool should work on most of the PB G5 lineup since they have similar specs)

**Comment by erpalma** [comment]
Thanks for the feedback!
