### ISSUE TITLE
Thinkpad T14 Gen 2

### ISSUE THREAD

**Issue by igoropaniuk** [erpalma/throttled#261]
Have anyone already tested it on T14 Gen 2?

**Comment by MarcvdSluys** [comment]
Do you have a working config for the T14G2?

**Comment by MarcvdSluys** [comment]
Oh, wow - I installed v0.9.2 first and it didn't do much.  Once I installed the latest git (v9999 on Gentoo), CPU frequency and temperatures surged, and the fan went into helicopter mode.  

Seems to work fine on my T14G2 with 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz - no further questions.
