### ISSUE TITLE
Running throttled on Fedora 35 Silverblue - working, but reports warnings

### ISSUE THREAD

**Issue by lakotamm** [erpalma/throttled#268]
I decided to give Fedora 35 Silverblue a ago. Throttled is one of my must-have tools, so I was happy to find out, that it works when compiled from source. That being said, the program reports some warnings, which I guess are caused by files going missing when the immutable OS-image is rebuilt.

> $ sudo systemctl status lenovo_fix.service 
> ● lenovo_fix.service - Stop Intel throttling
>      Loaded: loaded (/etc/systemd/system/lenovo_fix.service; enabled; vendor preset: disabled)
>      Active: active (running) since Mon 2021-09-20 13:09:44 CEST; 3min 34s ago
>    Main PID: 803 (python3)
>       Tasks: 2 (limit: 28340)
>      Memory: 24.3M
>         CPU: 255ms
>      CGroup: /system.slice/lenovo_fix.service
>              └─803 /opt/lenovo_fix/venv/bin/python3 /opt/lenovo_fix/lenovo_fix.py
> 
> Sep 20 13:09:44 fedora systemd[1]: Started Stop Intel throttling.
> **Sep 20 13:09:44 fedora python3[902]: modprobe: FATAL: Module configs not found in directory /lib/module/5.14.0-60.fc35.x86_64
> **Sep 20 13:09:44 fedora python3[803]: [W] Unable to obtain and validate kernel config.****
> Sep 20 13:09:44 fedora python3[803]: [I] Detected CPU architecture: Intel Comet Lake-U
> Sep 20 13:09:44 fedora python3[803]: [I] Trying to unlock MSR allow_writes.
> Sep 20 13:09:44 fedora python3[803]: [I] Loading config file.
> Sep 20 13:09:44 fedora python3[803]: [I] Starting main loop.

1. I installed the packages necessary for throttled using:
`sudo rpm-ostree install python3-cairo-devel cairo-gobject-devel gobject-introspection-devel dbus-glib-devel python3-devel libX11-devel`
`dnf` is replaced by `rpm-ostree`, `make` is installed by default.

2. I added a kernel command `msr.allow_writes=on` + rebooted

3. And afterwards, ran the `install.sh `script.

Are these warnings something to be afraid about? 

Thank you!

**Comment by erpalma** [comment]
There are some issues with retrieving kernel config and possibly loading the `msr` module by the tool. But I guess it is already loaded since you added that kernel command line. If throttled does not give you other errors you should be fine.
