### ISSUE TITLE
PKGBUILD (ArchLinux) not up to date with the package renaming

### ISSUE THREAD

**Issue by g3n35i5** [erpalma/throttled#287]
As mentioned in f4566d52d4a5fc1bce59ea55fd1237c35e2e17ba, the tool has been renamed from `lenovo_fix` to `throttled`.
This renaming hasn't been performed for the systemd service on ArchLinux, yet.

This results in
```
Failed to enable unit: Unit file throttled.service does not exist.
```

Moreover, the config file names, etc. haven't been renamed, too.

I'd suggest to rename all occurrences in [the PKGBUILD file](package/PKGBUILD).

**Comment by felixonmars** [comment]
The renaming happened in https://github.com/erpalma/throttled/commit/392f3f8ab93bd095495d8d9e574d986854328dd7 which isn't present in a release/tag yet. I'll perform the necessary update and leave an installation msg in next release as this is going to break user setup.
