### ISSUE TITLE
Problems on Fedora 37

### ISSUE THREAD

**Issue by oleg-rom** [erpalma/throttled#319]
Hi, obviously with new release of Fedora 37 it is not possible to install throttled. Are there any plans to fix this?

**Comment by adueppen** [comment]
The abn/throttled COPR is maintained by a community member and so not really in scope for this repo (although they do need to rebuild it for F37). For now I'm using https://copr.fedorainfracloud.org/coprs/tuxino/Blob/ instead.

**Comment by oleg-rom** [comment]
Thank you for your response.
